### ISSUE TITLE
As a client I want the MyParcel fields to be filled in when I manually create an order.

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#445] opened 2020-11-09 16:16 UTC
As a client I want the MyParcel fields to be filled in when I manually create an order.

[Screen record of steps](https://monosnap.com/file/vWgW76XC3nUfWVh8zypAHm2rbeFYBg)

**Comment by TimBlom** [comment] 2020-11-09 16:16
###

**Comment by TimBlom** [comment] 2020-11-09 16:17
Also PostNL-plugin

**Comment by Mitchell-MyParcel** [comment] 2020-11-10 10:55
Duplicate of #399

**Closed by Mitchell-MyParcel** 2020-11-10 10:55 UTC
Labels: duplicate
