### ISSUE TITLE
Auto Fill google/chrome address is not compatible with MyParcel address fields

### ISSUE THREAD

**Issue by YoranWattimena** [myparcelnl/woocommerce#1018] opened 2023-09-20 10:57 UTC
### Plugin version

4.21.0

### WooCommerce version

8.1.1

### WordPress version

6.2.2

### PHP version

8.1.22

### What went wrong?

When our clients use Google Chrome's autofill adres function, and then try to use it in our checkout (with MyParcel adres fields enabled) the house numbers/adress numbers are doubled. So for example: Street - Highwaystreet 23 | Number - 23. 
This means that we have to edit all the orders we got on a daily basis, which is a loss of time. 

Could you please fix this? Or make it compatible with the autofill function?

Chrome version: 116.0.5845.179

### Reproduction steps

1. Navigate to checkout
2. Click on autofill adres from the Google Chrome autofill function. 
3. See that the house numbers are doubled. Once in the street_field and in the number_field.

**Comment by EdieLemoine** [comment] 2023-12-01 10:19
Duplicate of #657

**Closed by EdieLemoine** 2023-12-01 10:19 UTC
Labels: bug
